#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

PATH="/usr/local/bin:$PATH"
export NODE_OPTIONS="--max_old_space_size=4096"

# Perform lint check on files in the staging area through .lintstagedrc configuration
pnpm exec lint-staged --concurrent 1